{{- if .Values.opensearch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: opensearch-init-{{ .Release.Revision }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: opensearch-init
    {{- include "foodios.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: opensearch-init
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-opensearch
        image: curlimages/curl:8.5.0
        command: ['sh', '-c']
        args:
        - |
          until curl -s http://opensearch:9200/_cluster/health | grep -q '"status"'; do
            echo "Waiting for OpenSearch..."
            sleep 5
          done
      containers:
      - name: init-opensearch
        image: curlimages/curl:8.5.0
        command: ['sh', '-c']
        args:
        - |
          set -e
          {{- if eq .Values.global.environment "production" }}
          RETENTION_DAYS=30
          {{- else }}
          RETENTION_DAYS=7
          {{- end }}

          echo "Creating ISM policy for ${RETENTION_DAYS}-day retention..."

          # Create ISM policy
          curl -X PUT "http://opensearch:9200/_plugins/_ism/policies/logs-retention-policy" \
            -H 'Content-Type: application/json' \
            -d "{
              \"policy\": {
                \"description\": \"Delete logs after ${RETENTION_DAYS} days\",
                \"default_state\": \"active\",
                \"states\": [
                  {
                    \"name\": \"active\",
                    \"actions\": [],
                    \"transitions\": [
                      {
                        \"state_name\": \"delete\",
                        \"conditions\": {
                          \"min_index_age\": \"${RETENTION_DAYS}d\"
                        }
                      }
                    ]
                  },
                  {
                    \"name\": \"delete\",
                    \"actions\": [
                      {
                        \"delete\": {}
                      }
                    ]
                  }
                ],
                \"ism_template\": [
                  {
                    \"index_patterns\": [\"logs-*\"],
                    \"priority\": 100
                  }
                ]
              }
            }"

          echo "Creating index template for logs..."

          # Create index template
          curl -X PUT "http://opensearch:9200/_index_template/logs-template" \
            -H 'Content-Type: application/json' \
            -d '{
              "index_patterns": ["logs-*"],
              "template": {
                "settings": {
                  "number_of_shards": 1,
                  "number_of_replicas": 0,
                  "index.refresh_interval": "5s",
                  "plugins.index_state_management.policy_id": "logs-retention-policy"
                },
                "mappings": {
                  "properties": {
                    "@timestamp": {
                      "type": "date"
                    },
                    "body": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    },
                    "log.level": {
                      "type": "keyword"
                    },
                    "service.name": {
                      "type": "keyword"
                    },
                    "resource": {
                      "properties": {
                        "service.name": {
                          "type": "keyword"
                        },
                        "deployment.environment": {
                          "type": "keyword"
                        },
                        "k8s.namespace": {
                          "type": "keyword"
                        }
                      }
                    },
                    "attributes": {
                      "properties": {
                        "pod_name": {
                          "type": "keyword"
                        },
                        "container_name": {
                          "type": "keyword"
                        },
                        "namespace": {
                          "type": "keyword"
                        },
                        "stream": {
                          "type": "keyword"
                        },
                        "log.file.path": {
                          "type": "keyword"
                        }
                      }
                    }
                  }
                }
              },
              "priority": 200
            }'

          echo "OpenSearch initialization complete"
{{- end }}
