services:
  bsky:
    working_dir: './repos/atproto/services/bsky/'
    build:
      - 'cd ../../packages/bsky'
      - 'pnpm install'
      - 'pnpm build'
    run:
      - 'node --enable-source-maps api.js'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
      - 'DD_TRACE_AGENT_URL' # docker-internal so can't access
    env_subst:
      - 's/@database/@localhost/'
      - 's#_URL=http://\([a-z]*\):#_URL=https://\1.dallan.inclan#' # actually use FQDN properly here
    env_override:
      BSKY_BLOB_CACHE_LOC: '/tmp/bsky-cache/'
      BSKY_BSYNC_PORT: 30020
      BSKY_BSYNC_URL: 'http://localhost:30020'
      BSKY_DATAPLANE_PORT: 30010
      BSKY_DATAPLANE_URLS: 'http://localhost:30010'
      BSKY_PORT: 25840
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'

