services:
  bgs:
    working_dir: './repos/indigo/'
    build:
      - 'echo "replace github.com/gocql/gocql => github.com/scylladb/gocql v1.14.4" >> go.mod'
      - go mod tidy
      - go mod vendor
    run:
      - 'docker compose cp bgs:/data/bigsky $local_service_tmp_dir/bigsky'
      - 'go run ./cmd/bigsky --api-listen localhost:24700 --data-dir $local_service_tmp_dir/bigsky'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's/@database/@localhost/'
    env_override:
      BGS_PORT: 24700 # this doesn't actually set the port; that's done by the commandline above and they should match
      BGS_METRICS_LISTEN: 'localhost:24710'
      # NB: hardcoded paths are stored in the carstore database
      DATA_DIR: '$local_service_tmp_dir/bigsky'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318'
  relay:
    working_dir: './repos/indigo/'
    build:
      - go mod tidy
      - go mod vendor
      - make build-relay-admin-ui
    run:
      - 'docker compose cp relay:/data/relay $local_service_tmp_dir/relay'
      - 'mkdir -p $local_service_tmp_dir/relay/events'
      - 'touch $local_service_tmp_dir/relay/events/evts-0'
      - 'go run ./cmd/relay serve --enable-db-tracing --enable-otel-tracing'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's/@database/@localhost/'
    env_override:
      RELAY_LOG_LEVEL: 'debug'
      RELAY_API_LISTEN: ':24720' # this doesn't actually set the port; that's done by the commandline above and they should match
      RELAY_METRICS_LISTEN: 'localhost:24730'
      RELAY_PERSIST_DIR: '$local_service_tmp_dir/relay/events'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318'
  bsky:
    working_dir: './repos/social-app/submodules/atproto/services/bsky/'
    build:
      - 'cd ../../'
      - 'pnpm --filter bsky... install'
      - 'pnpm --filter bsky... build'
      - 'cd services/bsky'
    run:
      - 'node --enable-source-maps api.js'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's/@database/@localhost/'
      - 's#_URL=http://\([a-z]*\):#_URL=https://\1.dallan.inclan#' # actually use FQDN properly here
    env_override:
      BSKY_BLOB_CACHE_LOC: '/tmp/bsky-cache/'
      BSKY_BSYNC_PORT: 30020
      BSKY_BSYNC_URL: 'http://localhost:30020'
      BSKY_DATAPLANE_PORT: 30010
      BSKY_DATAPLANE_URLS: 'http://localhost:30010'
      BSKY_PORT: 25840
      DD_TRACE_AGENT_URL: 'http://localhost:8126'
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'
  pds:
    working_dir: './repos/social-app/submodules/atproto/services/pds/'
    build:
      - 'cd ../../'
      - 'pnpm --filter pds... install'
      - 'pnpm --filter pds... build'
      - 'cd services/pds'
      - 'pnpm install'
    run:
      - 'docker compose cp pds:/pds $local_service_tmp_dir/pds'
      - 'node --enable-source-maps --require=./tracer.js index.js'
      # - 'docker compose cp $local_service_tmp_dir/pds pds:/pds'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's#_URL=http://\([a-z]*\):#_URL=https://\1.dallan.inclan#' # actually use FQDN properly here
    env_override:
      DD_TRACE_AGENT_URL: 'http://localhost:8126'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318'
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'
      PDS_BLOBSTORE_DISK_LOCATION: '$local_service_tmp_dir/pds/blobs'
      PDS_DATA_DIRECTORY: '$local_service_tmp_dir/pds'
      PDS_PORT: 25830
    volumes:
      - pds: '$local_service_tmp_dir/pds'
  social-app:
    working_dir: './repos/social-app/'
    build:
      - 'yarn atproto:install'
      - 'yarn atproto:build'
      - 'yarn install'
      - 'yarn intl:build'
      - 'yarn build-web'
      - 'cp conf/branding-bluesky.json bskyweb/branding-bluesky.json'
      - 'cp conf/branding.json bskyweb/'
      - 'cd bskyweb'
      - 'go mod download'
      - 'cd ..'
    run:
      - 'cd bskyweb'
      - 'go run ./cmd/bskyweb serve'
    watchers:
      - 'watchexec --postpone -w submodules/atproto -f package.json -f pnpm-lock.yaml -f pnpm-workspace.yaml -f "tsconfig/*" -f tsconfig.json --on-busy-update queue -- yarn atproto:install'
      - 'watchexec --postpone -w submodules/atproto/packages/api -w submodules/atproto/packages/common-web -w submodules/atproto/packages/syntax -w submodules/atproto/packages/lexicon -w submodules/atproto/packages/xrpc --on-busy-update queue -- yarn atproto:build'
      - 'watchexec --postpone -w src --on-busy-update queue -- yarn build-web'
      - 'watchexec --postpone -w bskyweb -f go.mod -f go.sym --on-busy-update queue -- bash -c "cd bskyweb ; go mod download"'
      - 'watchexec -w bskyweb --debounce 5sec --on-busy-update queue -- bash -c "cd bskyweb ; go run ./cmd/bskyweb serve"'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
      - 'IPCC_HOST' # http://ipcc:8080 won't work outside docker
    env_override:
      HTTP_ADDRESS: :8110
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'
      OTEL_PROPAGATORS: 'datadog,tracecontext,baggage'
      OTEL_EXPORTER_OTLP_INSECURE: true
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://127.0.0.1:4318'
  social-embed:
    working_dir: './repos/social-app/bskyweb'
    build:
      - 'cd ../'
      - 'yarn atproto:install'
      - 'yarn atproto:build'
      - 'yarn install'
      - 'yarn intl:build'
      - 'yarn build-embed'
      - 'cp conf/branding-bluesky.json bskyweb/branding-bluesky.json'
      - 'cp conf/branding.json bskyweb/'
      - 'cd bskyweb'
      - 'go mod download'
    run:
      - 'go run ./cmd/embedr serve'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
      - 'IPCC_HOST' # http://ipcc:8080 won't work outside docker
    env_override:
      HTTP_ADDRESS: :8111
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'
      OTEL_PROPAGATORS: 'datadog,tracecontext,baggage'
      OTEL_EXPORTER_OTLP_INSECURE: true
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://127.0.0.1:4318'
  social-link:
    working_dir: './repos/social-app/bskylink'
    build:
      - 'set | grep ANDROID'
      - 'yarn install'
      - 'yarn build'
    run:
      - 'node --enable-source-maps dist/bin.js'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's/@database/@localhost/'
    env_override:
      LINK_PORT: 30040
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'

  ozone:
    working_dir: './repos/ozone'
    build:
      - 'corepack enable'
      - 'yarn atproto:install'
      - 'yarn atproto:build'
      - 'yarn install'
    run:
      - 'set | grep "^[A-Z].*="'
      - 'yarn dev'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's/@database/@localhost/'
    env_override:
      PORT: 30050 # only used by dev mode
      OZONE_PORT: 30050
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'

