services:
  bsky:
    working_dir: './repos/social-app/submodules/atproto/services/bsky/'
    build:
      - 'cd ../../'
      - 'pnpm --filter bsky... install'
      - 'pnpm --filter bsky... build'
      - 'cd services/bsky'
    run:
      - 'node --enable-source-maps api.js'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's/@database/@localhost/'
      - 's#_URL=http://\([a-z]*\):#_URL=https://\1.dallan.inclan#' # actually use FQDN properly here
    env_override:
      BSKY_BLOB_CACHE_LOC: '/tmp/bsky-cache/'
      BSKY_BSYNC_PORT: 30020
      BSKY_BSYNC_URL: 'http://localhost:30020'
      BSKY_DATAPLANE_PORT: 30010
      BSKY_DATAPLANE_URLS: 'http://localhost:30010'
      BSKY_PORT: 25840
      DD_TRACE_AGENT_URL: 'http://localhost:8126'
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'
  pds:
    working_dir: './repos/social-app/submodules/atproto/services/pds/'
    build:
      - 'cd ../../'
      - 'pnpm --filter pds... install'
      - 'pnpm --filter pds... build'
      - 'cd services/pds'
      - 'pnpm install'
    run:
      - 'docker compose cp pds:/pds $local_service_tmp_dir/pds'
      - 'node --enable-source-maps --require=./tracer.js index.js'
      # - 'docker compose cp $local_service_tmp_dir/pds pds:/pds'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's#_URL=http://\([a-z]*\):#_URL=https://\1.dallan.inclan#' # actually use FQDN properly here
    env_override:
      DD_TRACE_AGENT_URL: 'http://localhost:8126'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318'
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'
      PDS_BLOBSTORE_DISK_LOCATION: '$local_service_tmp_dir/pds/blobs'
      PDS_DATA_DIRECTORY: '$local_service_tmp_dir/pds'
      PDS_PORT: 25830
    volumes:
      - pds: '$local_service_tmp_dir/pds'
  social-app:
    working_dir: './repos/social-app/bskyweb'
    build:
      - 'cd ../'
      - 'yarn atproto:install'
      - 'yarn atproto:build'
      - 'yarn install'
      - 'yarn intl:build'
      - 'yarn build-web'
      - 'cp conf/branding.json bskyweb/'
      - 'cd bskyweb'
      - 'go mod download'
    run:
      - 'go run ./cmd/bskyweb serve'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
      - 'IPCC_HOST' # http://ipcc:8080 won't work outside docker
    env_override:
      HTTP_ADDRESS: :8101
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'
  social-link:
    working_dir: './repos/social-app/bskylink'
    build:
      - 'set | grep ANDROID'
      - 'yarn install'
      - 'yarn build'
    run:
      - 'node --enable-source-maps dist/bin.js'
    env_exclude:
      - 'HOME'
      - 'HOSTNAME'
      - 'PATH'
      - 'PWD'
    env_subst:
      - 's/@database/@localhost/'
    env_override:
      LINK_PORT: 30040
      NODE_EXTRA_CA_CERTS: '$script_dir/certs/ca-certificates.crt'


