#!/bin/bash

# this is for convenience when scripting manually
# in a script, if utils.sh has has been sourced, rather call the source_env function

if [ "$0" = "${BASH_SOURCE[0]}" ]; then
  echo "This script must be sourced, not run directly." >&2
  exit 1
fi

export params_file="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" ; readlink ".env" || realpath ".env")"

echo "Reading variables from $params_file into the current environment"

set -o allexport
. "$params_file"
set +o allexport

