{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: {{ .Values.global.namespace }}
  labels:
    app: otel-collector
    {{- include "foodios.labels" . | nindent 4 }}
{{- end }}
