#!/usr/bin/env bash

script_path="`realpath "$0"`"
script_dir="$(cd `dirname "$script_path"`/.. ; pwd)"
. "$script_dir/utils.sh"
source_env

[ "$1" != "" ] && restore_dir="$1"
[ -d "$restore_dir" ] || { show_error "Syntax $0 [restore_dir]" "but restore_dir given ($restore_dir) is not directory" ; exit 1 ; }

RELAY_SECRETS_FILE="$script_dir/config/relay-secrets.env"
make $RELAY_SECRETS_FILE
. $RELAY_SECRETS_FILE

[ "$relayFQDN" == "" ] && { show_warning "Couldn't find relay domain" "from relayFQDN environment; please check $params_file" >&2 ; exit 1 ; }
[ "$RELAY_ADMIN_KEY" == "" ] && { show_warning "Couldn't find relay admin key" "from environment or secrets file; please check RELAY_ADMIN_KEY in $params_file and $script_dir/config/secrets-passwords.env" >&2 ; exit 1 ; }

function get_relay_auth() {
  echo -n "admin:${RELAY_ADMIN_KEY}" | base64
}

RELAY_ADMIN_AUTH=$(get_relay_auth)

show_heading "Taking down relay and appview" "relay, bsky and backup in order to drop relay and bsky volume and relay and bsky database and reindex"
docker compose down relay bsky backup
show_info --oneline "Dropping database" "relay"
docker compose exec database sh -c 'dropdb -U pg relay'
show_info --oneline "Dropping database" "bsky"
docker compose exec database sh -c 'dropdb -U pg bsky'
show_info --oneline "Downing relay" "and its volume"
docker compose down -v relay

show_info "Checking volume deletion" "for relay"
docker compose volumes relay | grep relay >/dev/null && {
  show_error "Error dropping volume" "relay - please investigate and adjust manually"
  exit 1
}

show_info "Recreating volumes" "relay and bsky"
docker compose create relay bsky

show_info "Recreating databases" "relay and bsky"

docker compose exec database sh -c 'createdb -U pg relay ; psql -U pg healthcheck -c "grant all privileges on database relay to pg"' || {
  show_error "Error creating database" "relay - please investigate and adjust manually"
  exit 1
}

docker compose exec database sh -c 'createdb -U pg bsky ; psql -U pg healthcheck -c "grant all privileges on database bsky to pg"' || {
  show_error "Error creating database" "bsky - please investigate and adjust manually"
  exit 1
}

show_info --oneline "Restarting backup" "and waiting for it to be ready"
docker compose up -d backup
wait_for_container backup

[ "$restore_dir" != "" ] && {
  show_heading "Restoring data" "including filesystem and databases"
  target_dir="$(docker compose exec backup sh -c "mktemp -dt restore-XXXXXX")"
  docker compose cp "$restore_dir/." backup:"$target_dir/."
  docker compose exec backup sh -c "cp -a $target_dir/data/relay/. /data/relay/"
  docker compose exec backup sh -c "cp -a $target_dir/data/bsky/. /data/bsky/"
  docker compose exec backup sh -c "pg_restore -U pg -d relay $target_dir/data/postgres/relay.pgdump"
  docker compose exec backup sh -c "pg_restore -U pg -d bsky $target_dir/data/postgres/bsky.pgdump"
}

show_heading "Restarting relay" "and waiting for it to be ready"
docker compose up -d relay
wait_for_container relay

show_heading "Recrawling pds" "from relay and adjusting limits"

make $script_dir/config/relay-secrets.env

show_info --oneline "Requesting crawl" "from relay before adjusting limits"
(
  . $script_dir/config/relay-secrets.env
  wget -qO- --method=POST --body-data="{\"hostname\": \"$pdsFQDN\"}" --header="Content-Type: application/json" --header="Authorization: Basic ${RELAY_ADMIN_AUTH}" "https://$relayFQDN/admin/pds/requestCrawl"
)

# TODO: set cursor to 0

show_info --oneline "Adjusting pds limits" "on relay"

./selfhost_scripts/adjust-relay-limits.sh

show_info --oneline "Triggering full sync" "from pds on relay"

./selfhost_scripts/request-relay-sync.sh

show_info --oneline "Restarting bsky" "and waiting for it to be ready"
docker compose up -d bsky
wait_for_container bsky

show_info "Relay and appview containers restarted" "but backfill indexing still needs to be triggered"

