{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
    {{- include "foodios.labels" . | nindent 4 }}
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicas | default 1 }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.port }}
          name: redis
        volumeMounts:
        - name: data
          mountPath: /data/
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- if .Values.redis.resources }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.redis.storage.storageClass }}
      storageClassName: {{ .Values.redis.storage.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.redis.storage.size | default "5Gi" }}
{{- end }}
