{{- if and .Values.global.tls.enabled .Values.global.tls.certIssuer .Values.global.tls.cloudflare.apiToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: {{ .Values.global.tls.cloudflare.apiToken }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.global.tls.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.global.tls.cloudflare.email | default .Values.global.tls.email }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.global.tls.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.global.tls.cloudflare.email | default .Values.global.tls.email }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
{{- end }}
